---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: car-demo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: car-demo
  policy:
    semver:
      range: '>=1.0.0'

